/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AbandonedCarts: typeof import('./src/components/analytics/AbandonedCarts.vue')['default']
    AddProductDialog: typeof import('./src/components/AddProductDialog.vue')['default']
    AdvancedSettings: typeof import('./src/components/settings/AdvancedSettings.vue')['default']
    AnalyticsPanel: typeof import('./src/components/analytics/AnalyticsPanel.vue')['default']
    AnalyticsSettings: typeof import('./src/components/settings/AnalyticsSettings.vue')['default']
    AnalyticsTable: typeof import('./src/components/analytics/AnalyticsTable.vue')['default']
    AppCommandPalette: typeof import('./src/components/AppCommandPalette.vue')['default']
    AppearanceSettings: typeof import('./src/components/settings/AppearanceSettings.vue')['default']
    AppSettingsDialog: typeof import('./src/components/settings/AppSettingsDialog.vue')['default']
    ChromePreview: typeof import('./src/components/chrome/ChromePreview.vue')['default']
    CollectionCombobox: typeof import('./src/components/CollectionCombobox.vue')['default']
    ConversionFunnel: typeof import('./src/components/analytics/ConversionFunnel.vue')['default']
    DeviceSplit: typeof import('./src/components/analytics/DeviceSplit.vue')['default']
    DocLink: typeof import('./src/components/DocLink.vue')['default']
    ExternalProviderCard: typeof import('./src/components/analytics/ExternalProviderCard.vue')['default']
    FooterLinkDialog: typeof import('./src/components/footer/FooterLinkDialog.vue')['default']
    FooterSettings: typeof import('./src/components/settings/FooterSettings.vue')['default']
    IntegrationCard: typeof import('./src/components/integrations/IntegrationCard.vue')['default']
    IntegrationDialog: typeof import('./src/components/integrations/IntegrationDialog.vue')['default']
    IntegrationList: typeof import('./src/components/integrations/IntegrationList.vue')['default']
    IntegrationLogo: typeof import('./src/components/integrations/IntegrationLogo.vue')['default']
    ItemAnalyticsDialog: typeof import('./src/components/analytics/ItemAnalyticsDialog.vue')['default']
    KpiTiles: typeof import('./src/components/analytics/KpiTiles.vue')['default']
    LandingPages: typeof import('./src/components/analytics/LandingPages.vue')['default']
    ListSkeleton: typeof import('./src/components/ListSkeleton.vue')['default']
    LiveViewCard: typeof import('./src/components/analytics/LiveViewCard.vue')['default']
    NavInspector: typeof import('./src/components/navigation/NavInspector.vue')['default']
    OptionRow: typeof import('./src/components/OptionRow.vue')['default']
    OrderProgress: typeof import('./src/components/orders/OrderProgress.vue')['default']
    OrderStateBadge: typeof import('./src/components/OrderStateBadge.vue')['default']
    PaymentSettings: typeof import('./src/components/settings/PaymentSettings.vue')['default']
    ProductEngagement: typeof import('./src/components/analytics/ProductEngagement.vue')['default']
    ProfileSettings: typeof import('./src/components/settings/ProfileSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesHeatmap: typeof import('./src/components/analytics/SalesHeatmap.vue')['default']
    SalesOverTime: typeof import('./src/components/analytics/SalesOverTime.vue')['default']
    SettingsAttach: typeof import('./src/components/settings/SettingsAttach.vue')['default']
    SettingsField: typeof import('./src/components/settings/SettingsField.vue')['default']
    SettingsLinkField: typeof import('./src/components/settings/SettingsLinkField.vue')['default']
    SettingsSecretField: typeof import('./src/components/settings/SettingsSecretField.vue')['default']
    ShippingSettings: typeof import('./src/components/settings/ShippingSettings.vue')['default']
    StatChip: typeof import('./src/components/analytics/StatChip.vue')['default']
    StoreSettings: typeof import('./src/components/settings/StoreSettings.vue')['default']
    TopProducts: typeof import('./src/components/analytics/TopProducts.vue')['default']
    TrackingHealthCard: typeof import('./src/components/analytics/TrackingHealthCard.vue')['default']
    TrafficSources: typeof import('./src/components/analytics/TrafficSources.vue')['default']
  }
}
