/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddProductDialog: typeof import('./src/components/AddProductDialog.vue')['default']
    AppPageHeader: typeof import('./src/components/AppPageHeader.vue')['default']
    AppSettingsDialog: typeof import('./src/components/settings/AppSettingsDialog.vue')['default']
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    BrandMark: typeof import('./src/components/settings/BrandMark.vue')['default']
    BulkBar: typeof import('./src/components/BulkBar.vue')['default']
    CoachTip: typeof import('./src/components/import/CoachTip.vue')['default']
    EditableValue: typeof import('./src/components/EditableValue.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    GatewayCard: typeof import('./src/components/settings/GatewayCard.vue')['default']
    GatewayConfig: typeof import('./src/components/settings/GatewayConfig.vue')['default']
    ImagesStep: typeof import('./src/components/import/steps/ImagesStep.vue')['default']
    ImportDialog: typeof import('./src/components/import/ImportDialog.vue')['default']
    ImportStepNav: typeof import('./src/components/import/ImportStepNav.vue')['default']
    ListPagination: typeof import('./src/components/ListPagination.vue')['default']
    MapStep: typeof import('./src/components/import/steps/MapStep.vue')['default']
    NavSection: typeof import('./src/components/NavSection.vue')['default']
    OrderProgress: typeof import('./src/components/OrderProgress.vue')['default']
    PageBody: typeof import('./src/components/PageBody.vue')['default']
    ProductBasics: typeof import('./src/components/product/ProductBasics.vue')['default']
    ProductOrganization: typeof import('./src/components/product/ProductOrganization.vue')['default']
    ProductPricing: typeof import('./src/components/product/ProductPricing.vue')['default']
    ProductStock: typeof import('./src/components/product/ProductStock.vue')['default']
    ProductStorefront: typeof import('./src/components/product/ProductStorefront.vue')['default']
    ProductSummaryPanel: typeof import('./src/components/product/ProductSummaryPanel.vue')['default']
    ProductThumb: typeof import('./src/components/import/ProductThumb.vue')['default']
    ProductTypeFields: typeof import('./src/components/product/ProductTypeFields.vue')['default']
    ReportHeader: typeof import('./src/components/ReportHeader.vue')['default']
    ReportStats: typeof import('./src/components/ReportStats.vue')['default']
    ReviewStep: typeof import('./src/components/import/steps/ReviewStep.vue')['default']
    RichTextField: typeof import('./src/components/RichTextField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunStep: typeof import('./src/components/import/steps/RunStep.vue')['default']
    SearchPalette: typeof import('./src/components/SearchPalette.vue')['default']
    SourceStep: typeof import('./src/components/import/steps/SourceStep.vue')['default']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
    StorefrontPreview: typeof import('./src/components/StorefrontPreview.vue')['default']
    Thumb: typeof import('./src/components/Thumb.vue')['default']
    UploadStep: typeof import('./src/components/import/steps/UploadStep.vue')['default']
    VariantDialog: typeof import('./src/components/VariantDialog.vue')['default']
    VariantEditor: typeof import('./src/components/VariantEditor.vue')['default']
    VariantImageImport: typeof import('./src/components/VariantImageImport.vue')['default']
    VariantMedia: typeof import('./src/components/VariantMedia.vue')['default']
  }
}
